name: Flight Price Monitor

on:
  schedule:
    # Runs every 30 minutes (UTC)
    # Adjust for Korea Standard Time (KST = UTC +9) as needed
    - cron: '*/30 * * * *'
  workflow_dispatch:
    inputs:
      origin:
        description: "출발 공항 코드 (예: ICN)"
        required: false
        default: "ICN"
      destination:
        description: "도착 공항 코드 (예: NRT)"
        required: false
        default: "NRT"

jobs:
  monitor-flights:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run flight monitor
        env:
          AMADEUS_API_KEY: ${{ secrets.AMADEUS_API_KEY }}
          AMADEUS_API_SECRET: ${{ secrets.AMADEUS_API_SECRET }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          ORIGIN: ${{ github.event.inputs.origin || 'ICN' }}
          DESTINATION: ${{ github.event.inputs.destination || 'NRT' }}
        run: |
          python flight_monitor.py

      - name: Log monitoring result
        if: always()
        run: |
          echo "모니터링 완료: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "다음 실행: 30분 후"
